# Generated by Django 5.1.15 on 2026-02-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('nav_placement', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('hidden', 'Hidden')], default='header', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['nav_placement', 'is_visible', 'order'], name='core_catego_nav_pla_ad359c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('template', models.CharField(blank=True, default='', max_length=100)),
                ('order_in_category', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('og_image', models.CharField(blank=True, default='', max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('audience_tags', models.JSONField(default=list)),
                ('intent_tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.page')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order_in_category'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('conditions', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.page')),
            ],
            options={
                'verbose_name': 'Page Block',
                'verbose_name_plural': 'Page Blocks',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['category', 'status', 'order_in_category'], name='core_page_categor_033366_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'published_at'], name='core_page_status_81eeb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_page_slug_per_category'),
        ),
        migrations.AddIndex(
            model_name='pageblock',
            index=models.Index(fields=['page', 'order'], name='core_pagebl_page_id_0696fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pageblock',
            index=models.Index(fields=['type'], name='core_pagebl_type_ad87aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='pageblock',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='unique_block_order_per_page'),
        ),
    ]
