# Generated by Django 5.1.15 on 2026-02-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_category_page_pageblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', max_length=200)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='media_assets/')),
                ('original_filename', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.TextField(blank=True, default='')),
                ('caption', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preview_image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview_for', to='core.mediaasset')),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='og_image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='og_image_pages', to='core.mediaasset'),
        ),
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.mediafolder')),
            ],
            options={
                'verbose_name': 'Media Folder',
                'verbose_name_plural': 'Media Folders',
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.mediafolder'),
        ),
        migrations.CreateModel(
            name='MediaAssetUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('field', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='core.mediaasset')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Media Asset Usage',
                'verbose_name_plural': 'Media Asset Usages',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_mediaa_content_4580ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'content_type', 'object_id', 'field'), name='unique_asset_usage')],
            },
        ),
        migrations.AddIndex(
            model_name='mediafolder',
            index=models.Index(fields=['parent', 'order'], name='core_mediaf_parent__472cc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediafolder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_folder_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['asset_type', 'status', 'created_at'], name='core_mediaa_asset_t_3f9fde_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['folder', 'asset_type', 'created_at'], name='core_mediaa_folder__7c09d9_idx'),
        ),
    ]
