# Generated by Django 5.1.15 on 2026-02-28 07:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_media_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(max_length=500)),
                ('to_path', models.CharField(max_length=500)),
                ('status_code', models.IntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'ordering': ['from_path'],
                'indexes': [models.Index(fields=['is_active', 'from_path'], name='core_redire_is_acti_6846ee_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_path',), name='unique_redirect_from_path')],
            },
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['is_active', 'type'], name='core_snippe_is_acti_6c39a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent', models.JSONField(default=dict)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=128)),
                ('is_bot_suspected', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'verbose_name_plural': 'Visitor Sessions',
                'indexes': [models.Index(fields=['last_seen_at'], name='core_visito_last_se_3e35fa_idx'), models.Index(fields=['created_at'], name='core_visito_created_302571_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_no', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.page')),
            ],
            options={
                'verbose_name': 'Page Revision',
                'verbose_name_plural': 'Page Revisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page', 'created_at'], name='core_pagere_page_id_4c44ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'revision_no'), name='unique_page_revision_no')],
            },
        ),
        migrations.CreateModel(
            name='BehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.visitorsession')),
            ],
            options={
                'verbose_name': 'Behavior Event',
                'verbose_name_plural': 'Behavior Events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['session', 'occurred_at'], name='core_behavi_session_8e4aa8_idx'), models.Index(fields=['event_type', 'occurred_at'], name='core_behavi_event_t_7eabf3_idx')],
            },
        ),
    ]
