# Generated by Django 6.0.2 on 2026-02-28 08:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_content_ops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider_type', models.CharField(choices=[('OpenAI', 'OpenAI'), ('Gemini', 'Gemini'), ('Claude', 'Claude')], max_length=20)),
                ('api_key', models.CharField(max_length=500)),
                ('organization_id', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['provider_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_id', models.CharField(help_text='Provider-side model identifier, e.g. gpt-4o', max_length=200)),
                ('input_price_per_1m_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='USD cost per 1 million input tokens', max_digits=12, null=True)),
                ('output_price_per_1m_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='USD cost per 1 million output tokens', max_digits=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIJobsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(default='core.ai', max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Error', 'Error')], default='Pending', max_length=20)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('costs', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.aimodel')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Jobs History',
                'verbose_name_plural': 'AI Jobs History',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['provider', 'model', 'status', 'timestamp'], name='core_aijobs_provide_726790_idx'), models.Index(fields=['user', 'timestamp'], name='core_aijobs_user_id_e44619_idx')],
            },
        ),
    ]
