# Generated by Django 6.0.2 on 2026-02-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ai_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order_in_category'], 'permissions': [('manage_content', 'Can create and edit pages via the inline CMS editor')], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='content_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
