# Generated by Django 6.0.2 on 2026-02-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_page_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='audience_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='page',
            name='intent_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
