# Generated by Django 6.0.2 on 2026-02-28 15:21

from django.db import migrations, models


def migrate_content_html_to_source(apps, schema_editor):
    """Migrate existing content_html to content_html_source."""
    Page = apps.get_model('core', 'Page')
    for page in Page.objects.all():
        if page.content_html:
            page.content_html_source = page.content_html
            page.save(update_fields=['content_html_source'])


def reverse_migration(apps, schema_editor):
    """Reverse migration: copy content_html_source back to content_html."""
    Page = apps.get_model('core', 'Page')
    for page in Page.objects.all():
        if page.content_html_source and not page.content_html:
            page.content_html = page.content_html_source
            page.save(update_fields=['content_html'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_page_audience_tags_alter_page_intent_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_html_layout',
            field=models.TextField(blank=True, default='', help_text='AI-generated Bootstrap layout'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_html_source',
            field=models.TextField(blank=True, default='', help_text='Source content edited in Quill'),
        ),
        migrations.RunPython(migrate_content_html_to_source, reverse_migration),
    ]
